### ISSUE TITLE
貌似不能兼容最新的版本

### ISSUE THREAD

**Issue by AndersonHJB** [Zhengqbbb/vuepress-plugin#13]
貌似不能兼容最新的版本
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/48122016/206828749-14fa444f-bc20-4a24-856f-f5330f44b92d.png">
<img width="813" alt="image" src="https://user-images.githubusercontent.com/48122016/206828756-66e8e01a-e44a-4783-8ce8-507a13ab2773.png">

**Comment by Zhengqbbb** [comment]
ok 看了一下 vuepress-next ISSUE 应该还是很不稳定 😵
预计这两天更新兼容到最新版本

**Comment by yupeshekhonov** [comment]
Also, getting a similar error. Looking forward to a fix. 

![image](https://user-images.githubusercontent.com/107192102/212023462-90fdacfd-a20f-4240-9e20-da64aced7c6e.png)

**Comment by Zhengqbbb** [comment]
@AndersonHJB @yupeshekhonov  
The latest version ⭐️v2.1.5⭐️ should be resolve the ISSUE
Please tell me if have question

**Comment by julien-blanchon** [comment]
I still get this error with 2.1.5

**Comment by Zhengqbbb** [comment]
> I still get this error with 2.1.5 on `vuepress-plugin-clipboard`

what is your vuepress version ?
I have used the vuepress-next latest version `2.0.0-beta.61`. The website and code is working. U can have try
https://github.com/Zhengqbbb/vuepress-plugin/tree/main/docs

**Comment by AndersonHJB** [comment]
> @AndersonHJB @yupeshekhonov 最新版本⭐️v2.1.5⭐️应该解决问题 请告诉我是否有问题

现在的解决方法：

<img width="691" alt="image" src="https://user-images.githubusercontent.com/48122016/222033319-02d02b39-28b9-415d-832d-b8ae4cbda27f.png">

**Comment by julien-blanchon** [comment]
Here is my `package.json`
<img width="597" alt="Screenshot 2023-03-01 at 21 43 59" src="https://user-images.githubusercontent.com/11278197/222260701-2203d8cb-6c1d-46d6-85a4-062f6bfb0e6c.png">

Still a `Plugin<PluginObject>` type error
<img width="250" alt="Screenshot 2023-03-01 at 21 44 29" src="https://user-images.githubusercontent.com/11278197/222260791-4734200a-dde7-4bcf-9dc6-08772d50271a.png">

And a `const utils_1 = require("@vuepress/utils");` `require()` error when building the site

**Comment by Zhengqbbb** [comment]
```json
{
    "@vuepress/bundler-vite": "2.0.0-beta.60",
    "@vuepress/cli": "2.0.0-beta.60",
    "@vuepress/client": "2.0.0-beta.60",
    "vuepress": "2.0.0-beta.49"
}
```

Your dependency version numbers are confusing and they should be consistent

`vuepress-plugin-clipboard` also have a fixed version number for compatibility with different versions.

see: https://vuepress.qbb.sh/changelog.html

Also I noticed that you use `vuepress-theme-gungnir`, there is my example repository
https://github.com/Zhengqbbb/vuepress-blog/tree/main/blog

If you have any questions, wecome to new a ISSUE
